#! /bin/sh

INFO() {
    echo -e "\033[1m[INSTALL] \033[0m $1"
}

ERROR() {
    echo -e "\033[1m[INSTALL] \033[0m $1"
}

CREATE_PARTITION() {

    DRIVE=$1
    PARTITION_SIZE=$2

    INFO "CREATING PARTITION: $DRIVE $SIZE"
    
    #CLEAN BOOT SECTOR
    dd if=/dev/zero of=$DRIVE bs=512 count=1 2> /dev/null > /dev/null

    SIZE=`fdisk -l $DRIVE 2> /dev/null | grep Disk | awk '{print $5}'`
echo $SIZE
    CYLINDERS=`echo $SIZE/255/63/512 | bc`

    {
    echo ,$PARTITION_SIZE,,*
    echo ,,,-
    } | sfdisk -H 255 -S 63 -C $CYLINDERS $DRIVE  2> /dev/null > /dev/null
    
    if [ $? -ne 0 ]; then
        ERROR "FAIL CREATE PARTITION"
        exit 0
    fi

    sleep 5
}

UPDATE_SYSTEM_CREATE() {
    PATH_REVISION=/camera/package/revisao/pkg/
    MOUNT=$1
               
    revtool ALL
    
    PKG_FILE=`sendrev print icop`
    
    INFO "COPIANDO CORE: $PKG_FILE"
    
    cp $PATH_REVISION/$PKG_FILE $MOUNT/var/log/setup/rev
}

UPDATE_SYSTEM() {
    MOUNT=$1

    echo "0.0" > $MOUNT/etc/system
    sync    
    upgraderev --root $MOUNT/
}

MAKE_FILESYSTEM() {
   
    DRIVE=$1
    PARTITION=$2
    #COUNT=1
    
    #while [ $PARTITION -ge $COUNT ]; do
    
        #mkfs.ext2 ${DRIVE}$COUNT 2> /dev/null > /dev/null
        mkfs.ext2 ${DRIVE}$PARTITION 2> /dev/null > /dev/null

        if [ $? -ne 0 ]; then
            ERROR "PROBLEMA CRIAR SISTEMA DE ARQUIVO"
            exit 0
        fi

        #INFO "CRIANDO SISTEMA DE ARQUIVO: ${DRIVE}$COUNT"
        INFO "CRIANDO SISTEMA DE ARQUIVO: ${DRIVE}$PARTITION"

        #tune2fs -c 3000 ${DRIVE}$COUNT 2> /dev/null > /dev/null
        tune2fs -c 3000 ${DRIVE}$PARTITION 2> /dev/null > /dev/null

        #COUNT=$((COUNT+1))
    #done
}

COPY_SYSTEM() {
    SRC=$1
    MOUNT=$2
    SYSTEM=$3

    INFO "INSTALANDO SISTEMA: $SYSTEM"
    mount $SRC $MOUNT
    tar xf $SYSTEM.tar -C $MOUNT &> /dev/null
    #cp -a $SYSTEM/* $MOUNT
    sync
}

CREATE_BOOTLOADER() {

    DRIVE=$1
    MOUNT=$2

    INFO "CRIANDO BOOTLOADER"
    lilo -b $DRIVE -r $MOUNT &> /dev/null
   
    if [ $? -ne 0 ]; then
        ERROR "PROBLEMA AO CRIAR BOOTLOADER"
        exit 0
    fi

}

CLEAN_SYSTEM() {
    MOUNT=$1

    INFO "LIMPEZA DO ARQUIVO DE INSTALACAO"
    # DEIXAR EM UM PASTA FIXA lilo.conf e boot
    rm -rf $MOUNT/etc/lilo.conf
    #rm -rf $MOUNT/boot/

    echo "" > $MOUNT/etc/HOSTNAME

    if [ ! -e $MOUNT/etc/modulo ]; then
        touch $MOUNT/etc/modulo
    fi

    echo "" > $MOUNT/etc/modulo

    if [ ! -e $MOUNT/etc/sensor ]; then
        touch $MOUNT/etc/sensor
    fi
    
    echo "" > $MOUNT/etc/sensor

    # zerar arquivos de log
    #echo "" > $MOUNT/var/log/cron
    #echo "" > $MOUNT/var/log/debug
    #echo "" > $MOUNT/var/log/dmesg
    #echo "" > $MOUNT/var/log/messages
    #echo "" > $MOUNT/var/log/secure
    #echo "" > $MOUNT/var/log/syslog
    #echo "" > $MOUNT/var/log/dropbear.log

    # echo "" > /var/log/btmp
    # echo "" > /var/log/faillog
    # echo "" > /var/log/lastlog
    # echo "" > /var/log/wtmp


    # PATCH DE LIMPEZA
    # limpeza do crontab
    # rm -rf /file_emb/home/
    # rm -rf /file_emb/media/
    # rm -rf /mnt/*
    # mkdir -p /mnt/pendrive
    # rm -rf /usr/X11*
    # rm -rf /var/X11
    # rm -rf /usr/man/
    # rm -rf /usr/doc/
    # rm -rf /usr/info/
    # rm -rf /usr/local
    # rm -rf /usr/src
    # rm -rf /usr/share/locale/~en/
    #
    # rm -rf /etc/motd
    # rm -rf /etc/issue*
    # rm -rf /etc/slackware-version
    # rm -rf /usr/share/zoneinfo
    # rm ~/.sqlite_history
    # rm ~/.bash_history
    # rm /var/log/setup/*.*
    # rm /var/log/maillog
    # rm /tmp/.ICE-unix
    # rm /tmp/.X11-unix
    
    # rm -rf /srv
    # rm -rf /media
    # rm -rf /mnt
}
